baseURL: "https://laos-blog.netlify.com/"
languageCode: "en-us"
title: "UKM LAOS"
theme: "laos-hugo"
metaDataFormat: "yaml"
contentDir: "content"
layoutDir: "layouts"
publishDir: "public"
# Site Menus
menu:
    # Navbar Menus
    nav:
        - name: "About"
          url: "about"
          weight: 2
        - name: "Contact"
          url: "contact"
          weight: 3
        - name: "Blog"
          url: "blog"
          weight: 4
        - name: "Mirror"
          url: "mirror"
          weight: 5
# Site Params
params:
    home: "Home"
    logo: "images/logo.png"
    dateFormat: "6 January 2006"
    # Meta data
    description: "UKM LAOS adalah Unit Kegiatan Mahasiswa di Universitas Jember yang berfokus pada teknologi berbasis Free/Libre Open Source Software (FLOSS)"
    author: "UKM LAOS"
    # Google Analitycs
    #googleAnalitycsID: "Your ID"

    # Banner Section
    banner:
        enable: true
        bgImage: "images/slider.jpg"
        heading: "Selamat Datang di UKM LAOS, Wahai"
        description: "Kami adalah Unit Kegiatan Mahasiswa di Universitas Jember yang berfokus pada teknologi, khususnya Free/Libre Open Source Software (FLOSS)."
        btn: true
        btnText: "Selengkapnya"
        btnURL: "#about"
        flipText:
            - title: "PELAJAR"
            - title: "DESAINER"
            - title: "DEVELOPER"

    # Homepage About Section
    about:
        enable: true
        title: "ABOUT ME"
        content: "Hai,<br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
        image: "images/about/about.jpg"

    # Call to Action
    cta:
        enable: true
        title: "SO WHAT YOU THINK ?"
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText: "Contact with me"
        btnURL: "/contact"

    # Portfolio Section On Homepage
    portfolio:
        enable: true
        title: "Latest Works"
        subtitle: "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    footer:
        socialIcon:
            - icon: "ion-social-facebook"
              url: "#"
            - icon: "ion-social-instagram"
              url: "#"
            - icon: "ion-social-linkedin"
              url: "#"
